In [1]:
import numpy as np

Define activation function with default threshold 0

In [2]:
def activation(x, threshold=0):
    return np.where(x > threshold, 1, np.where(x == threshold, x, 0))

Helper function to convert given pattern into bipolar form

In [3]:
toBipolar = lambda x: -1 if x == 0 else 1

Define input pattern

In [4]:
s_pattern1 = np.array([0, 1, 0, 1])
s_pattern2 = np.array([1, 0, 1, 0])

Construct bipolar input vector from input pattern

In [5]:
input_vector = np.array([list(map(toBipolar, s_pattern1)), list(map(toBipolar, s_pattern2))])
input_vector

array([[-1,  1, -1,  1],
       [ 1, -1,  1, -1]])

Define target patterns

In [6]:
t_pattern1 = np.array([0, 1])
t_pattern2 = np.array([1, 0])

Construct Bipolar Target Vector from Target Pattern

In [7]:
target_vector = np.array([list(map(toBipolar, t_pattern1)), list(map(toBipolar, t_pattern2))])
target_vector

array([[-1,  1],
       [ 1, -1]])

Compute weight matrix by Outer Product Rule

In [8]:
weight_matrix = np.dot(input_vector.T, target_vector)
weight_matrix

array([[ 2, -2],
       [-2,  2],
       [ 2, -2],
       [-2,  2]])

Forward Pass s -> t

In [9]:
t_in1 = np.dot(s_pattern1, weight_matrix)
t_in1

array([-4,  4])

Activate Value

In [10]:
t_1 = activation(t_in1)
t_1

array([0, 1])

Check if Activated Pattern is Same as Input Pattern

In [11]:
if np.array_equal(t_1, t_pattern1):
    print("Correct Response")
else:
    print("Incorrect Response")

Correct Response


In [12]:
t_in2 = np.dot(s_pattern2, weight_matrix)
t_in2

array([ 4, -4])

In [13]:
t_2 = activation(t_in2)
t_2

array([1, 0])

In [14]:
if np.array_equal(t_2, t_pattern2):
    print("Correct Response")
else:
    print("Incorrect Response")

Correct Response


Backward Pass t -> s

In [15]:
s_in1 = np.dot(t_pattern1, weight_matrix.T)
s_in1

array([-2,  2, -2,  2])

In [16]:
s_1 = activation(s_in1)
s_1

array([0, 1, 0, 1])

In [17]:
if np.array_equal(s_1, s_pattern1):
    print("Correct Response")
else:
    print("Incorrect Response")

Correct Response


In [18]:
s_in2 = np.dot(t_pattern2, weight_matrix.T)
s_in2

array([ 2, -2,  2, -2])

In [19]:
s_2 = activation(s_in2)
s_2

array([1, 0, 1, 0])

In [20]:
if np.array_equal(s_2, s_pattern2):
    print("Correct Response")
else:
    print("Incorrect Response")

Correct Response
